version = 3.11.0
runner.dialect = Scala3Future
project.git = true
assumeStandardLibraryStripMargin = true
align.stripMargin = true
align.preset = some
docstrings.style = SpaceAsterisk
docstrings.wrap = no
