rules = [
  OrganizeImports
]

OrganizeImports.groupedImports = Keep
OrganizeImports.expandRelative = true
OrganizeImports.removeUnused = false
OrganizeImports.targetDialect = Scala3
OrganizeImports.groups = [
  "re:javax?\\."
  "scala."
  "*"
  "tacit."
  "capybaraclaw."
]
